# (team, player, pos, round, pick)  round=None -> undrafted/waiver
R = {
"East Coast Wins Most":[("Baker Mayfield","QB",3,12),("Mike Evans","WR",3,5),("Brian Thomas Jr.","WR",6,1),
 ("Tony Pollard","RB",5,2),("Christian McCaffrey","RB",2,1),("Hunter Henry","TE",13,8),("Puka Nacua","WR",9,12),
 ("Kyren Williams","RB",9,10),("Josh Allen","QB",1,2),("Tyler Warren","TE",8,1),("Blake Corum","RB",None,None),
 ("Sam Darnold","QB",13,10),("Brian Robinson","RB",15,12),("Emanuel Wilson","RB",None,None),
 ("Andy Borregales","K",None,None),("Patriots","DEF",None,None),("Rashee Rice","WR",9,7)],
"It's Gonna Be Maye":[("Jacoby Brissett","QB",None,None),("Zay Flowers","WR",6,3),("Michael Wilson","WR",11,5),
 ("Zach Charbonnet","RB",7,7),("Tyler Allgeier","RB",15,1),("Trey McBride","TE",2,6),("Terry McLaurin","WR",3,7),
 ("Keenan Allen","WR",11,11),("Drake Maye","QB",10,6),("J.J. McCarthy","QB",14,6),("Juwan Johnson","TE",None,None),
 ("Devaughn Vele","WR",None,None),("Parker Washington","WR",None,None),("Jason Myers","K",None,None),
 ("Texans","DEF",None,None),("Devin Neal","RB",None,None)],
"Down to Pound":[("Dak Prescott","QB",4,1),("DeVonta Smith","WR",4,11),("Deebo Samuel","WR",9,2),
 ("Quinshon Judkins","RB",12,1),("Kareem Hunt","RB",None,None),("Harold Fannin Jr.","TE",None,None),
 ("Chris Olave","WR",7,2),("DJ Moore","WR",5,12),("Trevor Lawrence","QB",6,11),("Xavier Worthy","WR",4,12),
 ("Troy Franklin","WR",None,None),("Caleb Williams","QB",2,11),("Rhamondre Stevenson","RB",8,11),
 ("Shedeur Sanders","QB",None,None),("Cam Little","K",None,None),("Seahawks","DEF",None,None),("Dalton Kincaid","TE",11,2)],
"Hulleywood":[("Brock Purdy","QB",10,7),("George Pickens","WR",5,6),("Michael Pittman Jr.","WR",9,6),
 ("Travis Etienne Jr.","RB",8,7),("Jonathan Taylor","RB",2,7),("Mark Andrews","TE",6,7),("Ja'Marr Chase","WR",1,6),
 ("Wan'Dale Robinson","WR",11,6),("Jaylen Warren","RB",7,6),("Josh Downs","WR",12,7),("Tua Tagovailoa","QB",13,6),
 ("Keon Coleman","WR",10,3),("Jake Bates","K",16,5),("Harrison Butker","K",15,6),("Steelers","DEF",15,8),
 ("Buccaneers","DEF",None,None),("Tyreek Hill","WR",3,6)],
"Jersey Rum Hams":[("Jaxson Dart","QB",14,2),("Nico Collins","WR",5,9),("Emeka Egbuka","WR",5,11),
 ("Bucky Irving","RB",14,4),("Jacory Croskey-Merritt","RB",7,11),("Taysom Hill","TE",None,None),
 ("Derrick Henry","RB",2,2),("De'Von Achane","RB",9,11),("Justin Herbert","QB",4,2),("Tetairoa McMillan","WR",4,6),
 ("Kyle Monangai","RB",None,None),("Colston Loveland","TE",11,7),("Darren Waller","TE",None,None),
 ("Rome Odunze","WR",6,2),("Harrison Mevis","K",None,None),("Vikings","DEF",15,10)],
"Travis Swift":[("Matthew Stafford","QB",9,1),("Jerry Jeudy","WR",8,6),("Darius Slayton","WR",None,None),
 ("Bijan Robinson","RB",1,1),("Josh Jacobs","RB",2,12),("Dallas Goedert","TE",10,4),("Aaron Jones Sr.","RB",6,12),
 ("Jayden Reed","WR",13,1),("Cam Ward","QB",8,4),("Jordan Love","QB",10,12),("Travis Kelce","TE",8,12),
 ("Christian Watson","WR",None,None),("Ricky Pearsall","WR",6,6),("Cooper Kupp","WR",11,10),
 ("Brandon Aubrey","K",12,12),("Packers","DEF",16,12),("Tucker Kraft","TE",11,1)],
"Made America 2024":[("Jared Goff","QB",6,4),("CeeDee Lamb","WR",1,9),("Marvin Harrison Jr.","WR",3,11),
 ("Chase Brown","RB",8,2),("Rico Dowdle","RB",15,9),("Brenton Strange","TE",None,None),("Drake London","WR",2,4),
 ("Omarion Hampton","RB",3,9),("Kirk Cousins","QB",None,None),("Theo Johnson","TE",None,None),
 ("Kimani Vidal","RB",None,None),("Alvin Kamara","RB",4,4),("Audric Estime","RB",None,None),
 ("Eddy Pineiro","K",None,None),("Eagles","DEF",12,2),("Chiefs","DEF",14,7),("Cam Skattebo","RB",11,9)],
"Manhattan Meatpacker":[("Lamar Jackson","QB",1,3),("Jayden Higgins","WR",12,3),("A.J. Brown","WR",2,10),
 ("Breece Hall","RB",5,3),("RJ Harvey","RB",4,10),("Chig Okonkwo","TE",14,10),("T.J. Hockenson","TE",7,3),
 ("Tyrone Tracy Jr.","RB",10,10),("Jaydon Blue","RB",12,10),("Nick Chubb","RB",13,3),("Tee Higgins","WR",3,3),
 ("Michael Penix Jr.","QB",11,3),("Zach Ertz","TE",15,3),("Travis Hunter","WR",6,10),
 ("Ka'imi Fairbairn","K",16,10),("Broncos","DEF",9,3),("Braelon Allen","RB",8,10)],
"Mountain Hermits":[("Jalen Hurts","QB",1,5),("Romeo Doubs","WR",16,8),("Jordan Addison","WR",8,8),
 ("D'Andre Swift","RB",5,5),("Javonte Williams","RB",10,8),("Dalton Schultz","TE",None,None),
 ("Stefon Diggs","WR",7,5),("David Montgomery","RB",6,8),("Aaron Rodgers","QB",14,8),("Patrick Mahomes","QB",2,8),
 ("Kayshon Boutte","WR",None,None),("Tre Tucker","WR",None,None),("Elic Ayomanor","WR",None,None),
 ("Cameron Dicker","K",15,5),("Tyler Loop","K",None,None),("Bills","DEF",15,7),("Sam LaPorta","TE",4,8)],
"NY Kat Snatchers":[("Joe Burrow","QB",1,11),("Justin Jefferson","WR",1,10),("Amon-Ra St. Brown","WR",2,3),
 ("Saquon Barkley","RB",1,7),("Kenneth Walker III","RB",3,10),("AJ Barner","TE",None,None),
 ("Chris Godwin Jr.","WR",11,12),("Alec Pierce","WR",None,None),("C.J. Stroud","QB",7,10),
 ("Brock Bowers","TE",8,3),("Woody Marks","RB",None,None),("Quentin Johnston","WR",None,None),
 ("Bhayshul Tuten","RB",11,8),("Chimere Dike","WR",None,None),("Chase McLaughlin","K",16,1),
 ("Lions","DEF",None,None),("Daniel Jones","QB",13,12)],
"Randiculous":[("Bryce Young","QB",8,5),("Jaxon Smith-Njigba","WR",5,8),("Jameson Williams","WR",10,5),
 ("Jahmyr Gibbs","RB",1,8),("Ashton Jeanty","RB",2,5),("Jake Ferguson","TE",12,5),("Davante Adams","WR",4,5),
 ("Jaylen Waddle","WR",6,5),("Jauan Jennings","WR",9,8),("Isiah Pacheco","RB",5,7),("Geno Smith","QB",12,9),
 ("George Kittle","TE",3,8),("Hollywood Brown","WR",16,7),("Jordan Mason","RB",7,8),
 ("Daniel Carlson","K",None,None),("Cowboys","DEF",15,2),("Carson Wentz","QB",None,None)],
"Scared Hitless":[("Bo Nix","QB",2,9),("Courtland Sutton","WR",6,9),("Jakobi Meyers","WR",9,4),
 ("James Cook III","RB",3,4),("TreVeyon Henderson","RB",4,9),("Kyle Pitts Sr.","TE",None,None),
 ("Ladd McConkey","WR",7,4),("Kenny Gainwell","RB",None,None),("Tyler Shough","QB",None,None),
 ("DK Metcalf","WR",5,4),("Khalil Shakir","WR",10,9),("Jayden Daniels","QB",1,4),("Evan Engram","TE",8,9),
 ("Chuba Hubbard","RB",4,3),("Chris Boswell","K",16,4),("Rams","DEF",None,None),("Joe Mixon","RB",15,4)],
}
